# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 18:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='departure_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='trip',
            name='return_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
