# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20170929_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='from_person',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='to_person',
        ),
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='friends',
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
